---
dependencies:
  - role: chriswgerber.home_assistant.core

galaxy_info:
  author: Chris Gerber
  description: Xcel Meter Sensors for Home Assistant
  min_ansible_version: "2.4"
  license: None
  platforms:
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
