{{ ansible_managed | comment }}

- platform: snmp
  name: (USG) Gateway Uptime
  host: 192.168.1.1
  community: !secret snmp_community
  auth_key: !secret snmp_auth
  priv_key: !secret snmp_priv
  baseoid: 1.3.6.1.2.1.1.3.0
  accept_errors: true
  unit_of_measurement: seconds
  value_template: "{{ '{{((value | int) / 100) | int}}' }}"
