{{ ansible_managed | comment }}

- alias: When Conference Call On
  mode: single
  id: '1693334934141'
  description: Run automation when Conference Call Scene is toggled on.
  trigger:
    - platform: state
      entity_id:
        - input_boolean.conference_call_scene
      to: 'on'
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.new_scene
      metadata: {}
    - service: automation.turn_off
      data:
        stop_actions: true
      target:
        entity_id: automation.match_office_to_outside_color_temp
