---
galaxy_info:
  author: chriswgerber
  description: Configuration management for Home Assistant
  min_ansible_version: "2.4"
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
